p = r"D:\self\backend\app\services\kline_backfill.py"
s = open(p, encoding="utf-8").read()
old = """    names = names or {}\n    for i, code in enumerate(todo):\n        if not rebuild and store.has_enough(code, min_bars, path):\n            summary[\"skipped\"] += 1\n            continue\n        rows = fetch_history(code, source=source, lookback_days=lookback_days,\n                             name=names.get(code, \"\"))\n        if len(rows) < min_bars:\n            summary[\"failed\"] += 1\n            if len(summary[\"failed_codes\"]) < 20:\n                summary[\"failed_codes\"].append(code)\n        else:\n            summary[\"written_bars\"] += store.upsert_bars(rows, path)\n            summary[\"ok\"] += 1\n        if on_progress is not None and (i + 1) % 50 == 0:\n            on_progress(i + 1, len(todo), summary)\n        if len(todo) > batch_size and (i + 1) % batch_size == 0:\n            time.sleep(sleep_between)\n    summary[\"seconds\"] = round(time.time() - started, 1)\n    return summary"""
new = """    names = names or {}\n    n_total = len(todo)\n\n    def _one(code: str) -> tuple:\n        if not rebuild and store.has_enough(code, min_bars, path):\n            return code, \"skipped\", 0\n        rows = fetch_history(code, source=source, lookback_days=lookback_days,\n                             name=names.get(code, \"\"))\n        if len(rows) < min_bars:\n            return code, \"failed\", 0\n        return code, \"ok\", store.upsert_bars(rows, path)\n\n    done = 0\n    if workers and workers > 1 and n_total > workers:\n        pool = ThreadPoolExecutor(max_workers=int(workers))\n        try:\n            for code, status, n in pool.map(_one, todo):\n                if status == \"skipped\":\n                    summary[\"skipped\"] += 1\n                elif status == \"failed\":\n                    summary[\"failed\"] += 1\n                    if len(summary[\"failed_codes\"]) < 20:\n                        summary[\"failed_codes\"].append(code)\n                else:\n                    summary[\"ok\"] += 1\n                    summary[\"written_bars\"] += n\n                done += 1\n                if on_progress is not None and done % 50 == 0:\n                    on_progress(done, n_total, summary)\n        finally:\n            pool.shutdown(wait=False, cancel_futures=True)\n    else:\n        for i, code in enumerate(todo):\n            _, status, n = _one(code)\n            if status == \"skipped\":\n                summary[\"skipped\"] += 1\n            elif status == \"failed\":\n                summary[\"failed\"] += 1\n                if len(summary[\"failed_codes\"]) < 20:\n                    summary[\"failed_codes\"].append(code)\n            else:\n                summary[\"ok\"] += 1\n                summary[\"written_bars\"] += n\n            if on_progress is not None and (i + 1) % 50 == 0:\n                on_progress(i + 1, n_total, summary)\n            if len(todo) > batch_size and (i + 1) % batch_size == 0:\n                time.sleep(sleep_between)\n    summary[\"seconds\"] = round(time.time() - started, 1)\n    return summary"""
assert old in s, "anchor missing"
s = s.replace(old, new, 1)
s = s.replace("from datetime import datetime, timedelta", "from concurrent.futures import ThreadPoolExecutor\nfrom datetime import datetime, timedelta", 1)
s = s.replace("sleep_between: float = SLEEP_BETWEEN, source=None, on_progress=None,\n             names: dict | None = None) -> dict:", "sleep_between: float = SLEEP_BETWEEN, source=None, on_progress=None,\n             names: dict | None = None, workers: int = 1) -> dict:", 1)
open(p, "w", encoding="utf-8").write(s)
print("patched workers param")